# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-01 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('picname', models.CharField(max_length=255)),
                ('sys', models.IntegerField(default=1)),
                ('sysnum', models.CharField(max_length=32)),
                ('state', models.IntegerField(default=1)),
                ('user', models.CharField(max_length=32)),
                ('backuser', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('phonenum', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('cclicknum', models.IntegerField(default=0)),
                ('qclicknum', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
